# Obter a lista de andamentos
GET http://localhost:5000/api/andamentos
Content-Type: application/json
###


# Inserir novo andamento
POST http://localhost:5000/api/andamentos
Content-Type: application/json

{
 "dataHora": "2021-01-25T17:32:25.000Z",
 "titulo": "Andamento 1",
 "descricao": "Descricao do andamento 1",
 "requisicao": "5f6cba8798eca62ccce84ba7",
 "colaborador": "5f6cba8798eca62ccce84ba7"
}
###


# Alterar andamento
PUT http://localhost:5000/api/andamentos
Content-Type: application/json

{
 "_id": "6247851b8490d14dd8923e00",
 "dataHora": "2021-01-25T17:32:25.000Z",
 "titulo": "Requisicao 2",
 "descricao": "Descricao da requisicao 1"
}
###


# Excluir uma andamento
DELETE http://localhost:5000/api/andamentos/5f6cba8798eca62ccce84ba7
Content-Type: application/json
###


# Obter pelo id de andamento
GET http://localhost:5000/api/andamentos/5f6cba8798eca62ccce84ba7
Content-Type: application/json
###


# Obter andamentos filtrando
GET http://localhost:5000/api/andamentos/filtro/alterado
Content-Type: application/json
###


# Andamento com data inválida
POST http://localhost:5000/api/andamentos
Content-Type: application/json

{
 "dataHora": "2021-01-25T17:32:25.000Z",
 "titulo": "Andamento 1",
 "descricao": "Descricao do andamento 1",
 "requisicao": "5f6cba8798eca62ccce84ba7",
 "colaborador": "5f6cba8798eca62ccce84ba7"
}
###