# Obter a lista de colaboradores
GET http://localhost:3000/api/colaboradores
Content-Type: application/json
###


# Inserir novo colaborador
POST http://localhost:3000/api/colaboradores
Content-Type: application/json

{
 "nome": "Jaqson Dalbosco",
 "email": "jaqson@upf.br",
 "senha": "123"
}
###


# Alterar colaborador
PUT http://localhost:3000/api/colaboradores
Content-Type: application/json

{
 "_id": "5f6cba8798eca62ccce84ba7",
 "nome": "Jaqson alterado",
 "email": "jaqson@teste.com"
}
###


# Excluir um colaborador
DELETE http://localhost:3000/api/colaboradores/5f6cba8798eca62ccce84ba7
Content-Type: application/json
###


# Obter pelo id de colaborador
GET http://localhost:3000/api/colaboradores/5f6cba8798eca62ccce84ba7
Content-Type: application/json
###


# Obter colaboradores filtrando
GET http://localhost:3000/api/colaboradores/filtro/alterado
Content-Type: application/json
###


# Colaborador sem nome requerido.
POST http://localhost:3000/api/colaboradores
Content-Type: application/json

{
 "nome": "",
 "email": "jaqson@upf.br",
 "senha": "123"
}
###


# Colaborador com email duplicado.
POST http://localhost:3000/api/colaboradores
Content-Type: application/json

{
 "nome": "Jaqson",
 "email": "jaqson@upf.br",
 "senha": "123"
}
###
