@apiUrl = http://localhost:5000/api/andamentos
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjlhOTczNWFhMjhjZmQwNjFjNmI4NTkiLCJub21lIjoiSmFxc29uIGFsdGVyYWRvIiwiaWF0IjoxNjU0OTA0MzY0LCJleHAiOjE2NTQ5MDc5NjR9.VeGkplweoesZztncWIGLN5W-vkAu-Dp4K10DZKdyqIQ


# Obter a lista de andamentos
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Inserir novo andamento
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "dataHora": "2021-01-25T17:32:25.000Z",
 "titulo": "Andamento um",
 "descricao": "Descricao do andamento um",
 "requisicao": "5f6cba8798eca62ccce84ba7",
 "colaborador": "5f6cba8798eca62ccce84ba7"
}
###


# Alterar andamento
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "6247851b8490d14dd8923e00",
 "dataHora": "2021-01-25T17:32:25.000Z",
 "titulo": "Requisicao dois",
 "descricao": "Descricao da requisicao dois"
}
###


# Excluir uma andamento
DELETE {{apiUrl}}/5f6cba8798eca62ccce84ba7
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter pelo id de andamento
GET {{apiUrl}}/5f6cba8798eca62ccce84ba7
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter andamentos filtrando
GET {{apiUrl}}/filtro/dois
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Andamento com data inválida
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "titulo": "Andamento 1",
 "descricao": "Descricao do andamento 1",
 "requisicao": "5f6cba8798eca62ccce84ba7",
 "colaborador": "5f6cba8798eca62ccce84ba7"
}
###