@apiUrl = http://localhost:5000/api/colaboradores
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjlhOTczNWFhMjhjZmQwNjFjNmI4NTkiLCJub21lIjoiSmFxc29uIGFsdGVyYWRvIiwiaWF0IjoxNjU0MzAwMTc5LCJleHAiOjE2NTQzMDM3Nzl9.KqwInBnvY_dlGaK4tfeebxaq5cXEfVLgKYFufyEP7Ew


# Obter a lista de colaboradores
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Inserir novo colaborador
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "Rian Tedesco",
 "email": "rian@upf.br",
 "senha": "123"
}
###


# Alterar colaborador
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "629a9735aa28cfd061c6b859",
 "nome": "Jaqson alterado",
 "email": "jaqson@teste2.com",
 "senha": "12345"
}
###


# Excluir um colaborador
DELETE {{apiUrl}}/623526a2042f9a3f225e5fe0
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter pelo id de colaborador
GET {{apiUrl}}/623526a2042f9a3f225e5fe0
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter colaboradores filtrando
GET {{apiUrl}}/filtro/alterado
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Colaborador sem nome requerido.
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "",
 "email": "jaqson@upf.br",
 "senha": "123"
}
###


# Colaborador com email duplicado.
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "Jaqson",
 "email": "jaqson@upf.br",
 "senha": "123"
}
###


# Autenticação de colaborador
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "jaqson@teste2.com",
    "senha": "12345"
}
###
