@apiUrl = http://localhost:5000/api/requisicoes
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEzZmQxMjM1MDJlZWI4NjBhZjUxNmYiLCJub21lIjoiUmlhbiBUZWRlc2NvIiwiaWF0IjoxNjU1NTA2NDg0LCJleHAiOjE2NTU1MTAwODR9.6YuEWkZ7jyhgaa29zSliQ7WFj6v-NKEsQ4M4muY2CVM


# Obter a lista de requisicoes
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Inserir nova requisicao
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "titulo": "Requisicao um",
 "descricao": "Descricao da requisicao um",
 "dataHoraCriada": "2022-05-20",
 "status": "Aberto",
 "prazoAtendimento": "2022-05-20",
 "tipoRequisicao": "62a3fe6b68d91ea466e26d54",
 "solicitante": "62a3fe5368d91ea466e26d4d"
}
###


# Alterar requisicao
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "5f6cba8798eca62ccce84ba7",
 "titulo": "Requisicao dois",
 "descricao": "Descricao da requisicao dois",
 "dataHoraCriada": "2022-05-20",
 "status": "Cancelado",
 "prazoAtendimento": "2021-01-25T17:32:25.000Z"
}
###


# Excluir uma requisicao
DELETE {{apiUrl}}/5f6cba8798eca62ccce84ba7
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter pelo id de requisicao
GET {{apiUrl}}/62ace9d22be76e3e0f3e36dc
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter requisicoes filtrando
GET {{apiUrl}}/filtro/dois
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Requisicao com data inválida
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "titulo": "Requisicao 6",
 "descricao": "Descricao da requisicao 1",
 "status": "Aguardando",
 "prazoAtendimento": "2021-01-25T17:32:25.000Z",
 "tipoRequisicao": "5f6cba8798eca62ccce84ba7",
 "solicitante": "5f6cba8798eca62ccce84ba7"
}
###