@apiUrl = http://localhost:5000/api/solicitantes
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjlhOTczNWFhMjhjZmQwNjFjNmI4NTkiLCJub21lIjoiSmFxc29uIGFsdGVyYWRvIiwiaWF0IjoxNjU0MzAwMTc5LCJleHAiOjE2NTQzMDM3Nzl9.KqwInBnvY_dlGaK4tfeebxaq5cXEfVLgKYFufyEP7Ew


# Obter a lista de solicitantes
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Inserir novo solicitante
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "Jaqson Dalbosco",
 "email": "jaqson@upf.br",
 "senha": "123"
}
###


# Alterar solicitante
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "5f6cba8798eca62ccce84ba7",
 "nome": "Jaqson alterado",
 "email": "jaqson@teste.com"
}
###


# Excluir um solicitante
DELETE {{apiUrl}}/5f6cba8798eca62ccce84ba7
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter pelo id de solicitante
GET {{apiUrl}}/5f6cba8798eca62ccce84ba7
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter solicitantes filtrando
GET {{apiUrl}}/filtro/alterado
Content-Type: application/json
x-auth-token: {{authToken}}
###