@apiUrl = http://localhost:5000/api/solicitantes
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmEzZmQxMjM1MDJlZWI4NjBhZjUxNmYiLCJub21lIjoiUmlhbiBUZWRlc2NvIiwiaWF0IjoxNjU1NTA2NDg0LCJleHAiOjE2NTU1MTAwODR9.6YuEWkZ7jyhgaa29zSliQ7WFj6v-NKEsQ4M4muY2CVM

# Obter a lista de solicitantes
GET {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Inserir novo solicitante
POST {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "nome": "Solicitante um",
 "email": "solicitanteum@upf.br",
 "senha": "12345"
}
###


# Alterar solicitante
PUT {{apiUrl}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "5f6cba8798eca62ccce84ba7",
 "nome": "Solicitante dois",
 "email": "solicitantedois@teste.com",
 "senha": "12345"
}
###


# Excluir um solicitante
DELETE {{apiUrl}}/5f6cba8798eca62ccce84ba7
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter pelo id de solicitante
GET {{apiUrl}}/5f6cba8798eca62ccce84ba7
Content-Type: application/json
x-auth-token: {{authToken}}
###


# Obter solicitantes filtrando
GET {{apiUrl}}/filtro/dois
Content-Type: application/json
x-auth-token: {{authToken}}
###